BOARD_SYSTEMIMAGE_EXTFS_INODE_COUNT := 8192
BOARD_PRODUCTIMAGE_EXTFS_INODE_COUNT := 6144
BOARD_SYSTEM_EXTIMAGE_EXTFS_INODE_COUNT := 4096
BOARD_VENDORIMAGE_EXTFS_INODE_COUNT := 2048
BOARD_ODMIMAGE_EXTFS_INODE_COUNT := 1024
